name: Deploy to Netlify

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build hook
        run: curl -s -X POST "https://api.netlify.com/build_hooks/6a400801af6b1138cc710d0d"
